### ISSUE TITLE
Committing a Vote- Step 2 in Walkthrough

### ISSUE THREAD

**Issue by Ethereum1227** [AdChain/AdChainRegistryDapp#165]
"The filtered domains are all in the Voting Commit stage."
<img width="1181" alt="screen shot 2018-04-03 at 10 46 45 am" src="https://user-images.githubusercontent.com/35276813/38266202-e60c0e20-372c-11e8-8f6f-c9de64eb4048.png">

However, the image shows domains in various other stages such as "In Registry", "Reveal-Pending", 
and "Application (Pending)".

**Comment by eduardo-munoz** [comment]
@Ethereum1227 

We use a live feed for this. It is too complicated to use screenshots because of the different screen dimensions.

We have 2 options: 

1) We change the verbiage to `The filtered domains will be shown in Voting Commit stage.`
2) We use screenshots and center them on the screen. Therefore, it won't be in its correct position.

I can explain these in person too.
