### ISSUE TITLE
TrollBox Admin Icon

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#65]
In order to regulate the trollbox, we propose an Admin icon where whitelisted wallet addresses have an admin icon next to their message.

**Comment by miguelmota** [comment]
we'd need a user login system in order to do this (like how liqui or polo required users to log in to participate). The current implementation was a quick hack using firebase as the backend which gives the public read/write access, so in theory they'd be able to spoof the username/wallet address for the trollbox. If it get out of hand, then we'd have to disable it completely until we do user account management

**Comment by eduardo-munoz** [comment]
Understood @miguelmota
